# Generated by Django 4.1.4 on 2022-12-25 14:25

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_title', models.CharField(max_length=252)),
                ('description', ckeditor.fields.RichTextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=222)),
            ],
        ),
        migrations.CreateModel(
            name='MyPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=300)),
                ('project_image', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=-1, scale=None, size=[340, 210], upload_to='portfolio/')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=-1, scale=None, size=[455, 268], upload_to='user/')),
                ('name', models.CharField(max_length=500)),
                ('job', models.CharField(max_length=900)),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='DetailPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=400)),
                ('worked_lang', models.CharField(max_length=500)),
                ('project_url', models.URLField()),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='apps.myportfolio')),
            ],
        ),
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=300)),
                ('lastname', models.CharField(max_length=400)),
                ('age', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('languages', models.CharField(max_length=400)),
                ('course_name', models.CharField(max_length=400)),
                ('studied_in', models.CharField(max_length=400)),
                ('res_desc', ckeditor_uploader.fields.RichTextUploadingField()),
                ('prof_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.profile')),
            ],
            options={
                'verbose_name': 'About',
            },
        ),
    ]
