# Generated by Django 4.1.4 on 2022-12-25 22:12

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_secondresume'),
    ]

    operations = [
        migrations.CreateModel(
            name='LangImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_lang', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
